{% set name = "BISCUIT" %}
{% set version = "0.3.5.20180313" %}
{% set hash = "56f8eee700de8a484487a615f85bf4cfe651bc4159737293c9921486226ea637" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zwdzwd/biscuit/releases/download/v{{ version }}/release-source.zip
  fn: release-source.zip
  sha256: {{ hash }}

build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib {{ CONDA_ZLIB }}*
    - ncurses {{ CONDA_NCURSES }}*

  run:
    - libgcc # [not osx]
    - zlib {{ CONDA_ZLIB }}*
    - ncurses {{ CONDA_NCURSES }}*

test:
  commands:
    - biscuit 2>&1 | grep 'Usage'

about:
  home: https://github.com/zwdzwd/biscuit
  license: MIT
  summary: 'Tools for mapping and analyzing bisulfite sequences.'